Migrations
tijsverkoyen/capistrano-sumo pull request #7
Opened 2017-09-27 11:10 UTC by StijnVrolijk

This PR adds migrations to our deploy script. This is capistrano 3 conversion of the migration tasks in https://github.com/sumocoders/forkcms_deploy

2017-09-29 09:31 UTC, tijsverkoyen requested changes

2017-09-29 09:31 UTC, tijsverkoyen commented on lib/maintenance/.htaccess
> +# All url's will be see the maintenance page (index.html)
typo

2017-09-29 09:31 UTC, tijsverkoyen commented on lib/capistrano/tasks/migrations.rake
> +    task :prepare do
I would separate this in specific methods, so they have less responsibility

2017-09-29 09:31 UTC, tijsverkoyen commented on lib/capistrano/tasks/migrations.rake
> +            invoke 'sumo:migrations:backup_database'
Wouldn't it be better, more logical to have a backup-task in the db-namespace?

2017-09-29 09:31 UTC, tijsverkoyen commented on lib/capistrano/tasks/migrations.rake
> +                  execute :php, "#{release_path}/bin/console forkcms:locale:import -f #{migrationpath}/#{filename}"
This is fork specific, so I would PR the whole change to tijsverkoyen/capistrano-forkcms instead.

2017-09-29 09:31 UTC, tijsverkoyen commented on lib/capistrano/tasks/migrations.rake
> +                  execute :php, "#{migrationpath}/#{filename}"
I would create separate tasks for locale, php-scripts, SQL-updates

2017-09-29 09:31 UTC, tijsverkoyen commented on lib/capistrano/sumo/defaults.rb
> +  after :updated, 'sumo:migrations:prepare'
I think it would be more logical to invoke this in the namespace itself instead of calling it here.

2017-10-03 12:25 UTC, StijnVrolijk commented
Created some PR's on https://github.com/tijsverkoyen/capistrano-forkcms/

2017-10-03 12:25 UTC, closed without merging